### ISSUE TITLE
Support to insert dynamic version info into other files than just pyproject.toml

### ISSUE THREAD

**Issue by dalito** [ninoseki/uv-dynamic-versioning#33]
Thanks for creating and maintaining this package!

In a few projects, I have found a special feature of poetry-dynamic-versioning very useful. Via a [config section](https://github.com/mtkennerly/poetry-dynamic-versioning/tree/master?tab=readme-ov-file#configuration) `[tool.poetry-dynamic-versioning.substitution]` it is possible to inject the version into selected files (e.g. schema-files or documentation files).

It seems that the feature is not yet available in your package. Would you support adding it?

**Comment by ninoseki** [comment]
Could you check "Version Build Hook" in this doc?
https://github.com/ninoseki/uv-dynamic-versioning/blob/main/docs/version_source.md

I think it's enough.

**Comment by dalito** [comment]
Yes, it is! By using the "pattern" it is possible to substitute the version into an arbitrary file.

For example to substitute the version into this line in `src/schema.yaml`:

```yaml
...
version: "0.0.0"  # Managed by dynamic-versioning. Don't change this line!
...
```

The pyproject.tom file needs this section

```toml
[tool.hatch.build.hooks.version]
path = "src/schema.yaml"
pattern = """^(?:version:?\\s*\\")(?P<version>\\S*)(?:\\"\\s*# Managed by dynamic-versioning.).*$"""
```

In contrast to poetry-dynamic-versioning the substitution is limited to a single file. But this is all I need currently.
