### ISSUE TITLE
Metadata dependencies breaks `uv add` command.

### ISSUE THREAD

**Issue by Ox54** [ninoseki/uv-dynamic-versioning#34]
Hi there!  Thanks for this library! One issue i'm seeing is that after I set dynamic to version and dependencies, I can no longer run `uv add`, as it errors with:

> ValueError: 'dependencies' is dynamic but already listed in [project].

```toml
[project]
name = "blah"
dynamic = ["version", "dependencies"]

...
[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
  "some-child=={{ version }}"
]
```
