### ISSUE TITLE
Error in parsing `pattern` regex

### ISSUE THREAD

**Issue by Paul-AUB** [ninoseki/uv-dynamic-versioning#36]
Using this configuration:

```toml
[build-system]
requires = ["hatchling>=1.14.1,<2", "uv-dynamic-versioning>=0.4.0,<0.5.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.hooks.version]
path = "pilot_python/_version.py"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "semver"
pattern =  "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?$"

```

When invoking `uv build`, I get this pydantic validation error:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Project
tool.uv-dynamic-versioning.pattern
  Input should be 'default' or 'default-unprefixed' [type=enum, input_value='^(?P<base>\\d+\\.\\d+\\....(?P<revision>\\d+)?))?$', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/enum
```

However, it seems according to uv-dynamic-versioning documentation that a regex pattern *can* be provided. Maybe there is an issue in the validation of the pydantic field ?

Maybe somewhere like

```
class Pattern(Enum):
    """
    Regular expressions used to parse tags as versions.
    """

    Default = "default"
    """Default pattern, including `v` prefix."""
    DefaultUnprefixed = "default-unprefixed"
    """Default pattern, but without `v` prefix."""
```
